### ISSUE TITLE
June & July 2022 Contribution - Help and answer the community in Discord from the beginning

### ISSUE THREAD

**Issue by GuiGou12358** [AlgemDeFi/Algyors-Program#1]
From the beginning of Algem, I answered the community about different questions and issues in Discord

Discord Username: @GuiGou#1021
Twitter Username: @GuiGou12358
EVM Wallet Address: 0x873De45Cb8453144a8BC76c2916DD9c52a9Bdb34

**Comment by Gunit2481** [comment]
Hi GuiGou,

Thank you for submitting your contributions. Points were added to the spreadsheet.

Please, for the next month, try to follow the guidelines and keep everything to one issue.

E.g.: 
1. Community Management
2. Algem's envoy
3. The Professor

It's much easier for us to evaluate correctly your work. 💪

Thank you! 

I have added #2, #3, #4 & #5 under this one
