### ISSUE TITLE
July 2022 contribution - Algem Thai ( ChikaIzumi)

### ISSUE THREAD

**Issue by ChikaIzumi** [AlgemDeFi/Algyors-Program#10]
Discord Usename : ChikaIzumi#0784
Twitter Username : @Algem_Thai / @NyiNyiW18365837
EVM wallet address:  0x795712AeD2fe361b3623861903c916c8596E2733

Contribution : 

1. **Community Managemen**t

- Help and Active in the multiple Discord channels 
 
Here're as sneak-peeks 👀

![IMG_20220808_223652](https://user-images.githubusercontent.com/110775141/183463413-87d88f37-2f9c-4642-8520-63fdbc6fbc05.jpg)
![IMG_20220808_223928](https://user-images.githubusercontent.com/110775141/183463434-128d43d7-9daf-41c6-b613-27b419cb435a.jpg)
![IMG_20220808_223451](https://user-images.githubusercontent.com/110775141/183463461-5805e510-a566-42dc-929f-84de0c04b893.jpg)

- Create and Manage the local community on Twitter and Medium.

Twitter profile link : https://twitter.com/Algem_Thai?s=09
Medium profile link : https://medium.com/@Algem_Thai 

2. **VSM**

- https://medium.com/@Algem_Thai/algem-%E0%B9%80%E0%B8%9B%E0%B8%B4%E0%B8%94%E0%B8%95%E0%B8%B1%E0%B8%A7%E0%B8%AD%E0%B8%A2%E0%B9%88%E0%B8%B2%E0%B8%87%E0%B9%80%E0%B8%9B%E0%B9%87%E0%B8%99%E0%B8%97%E0%B8%B2%E0%B8%87%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%9A%E0%B8%99-polkadot-parachain-%E0%B8%97%E0%B8%B5%E0%B9%88%E0%B8%97%E0%B8%B0%E0%B8%A2%E0%B8%B2%E0%B8%99%E0%B8%82%E0%B8%B6%E0%B9%89%E0%B8%99-astarnetwork-868f58405e16

- https://medium.com/@Algem_Thai/algem-%E0%B8%9C%E0%B9%88%E0%B8%B2%E0%B8%99-quantstamp-%E0%B8%97%E0%B8%B5%E0%B9%88%E0%B8%AA%E0%B9%8D%E0%B8%B2%E0%B8%84%E0%B8%B1%E0%B8%8D-smart-contract-%E0%B9%81%E0%B8%A5%E0%B8%B0%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%95%E0%B8%A3%E0%B8%A7%E0%B8%88%E0%B8%AA%E0%B8%AD%E0%B8%9A%E0%B8%84%E0%B8%A7%E0%B8%B2%E0%B8%A1%E0%B8%9B%E0%B8%A5%E0%B8%AD%E0%B8%94%E0%B8%A0%E0%B8%B1%E0%B8%A2-5c71ef1d7e11

-https://discord.com/channels/949531419619766332/984945191377059930/1002236133310222367

-https://discord.com/channels/949531419619766332/984945191377059930/1002962269698785393

-https://discord.com/channels/949531419619766332/984945191377059930/1002849831561220148

-https://discord.com/channels/949531419619766332/984945191377059930/1002855376825360434

3. **Artistic contents(meme)**

I hope my memes are meaningful and fun for the community.

- https://discord.com/channels/949531419619766332/949539197323194478/995216209966542848
- https://discord.com/channels/949531419619766332/949539197323194478/995235231185522688
- https://discord.com/channels/949531419619766332/949539197323194478/998383968447647816
- https://discord.com/channels/949531419619766332/949539197323194478/999232293090623508
- https://discord.com/channels/949531419619766332/949539197323194478/999537474101592104
- https://discord.com/channels/949531419619766332/949539197323194478/1000974799323009044

**Comment by Gunit2481** [comment]
Hi Chikalzumi,

Thank you for your contributions, points were added to the spreadsheet.

Keep up the hard work. 💪
