### ISSUE TITLE
June / July 2022 Contribution - Algem Vietnam (Okinawa Oreo Cream Milk Tea)

### ISSUE THREAD

**Issue by OkinawaOreoCreamMilkTea** [AlgemDeFi/Algyors-Program#11]
Hello Algem admins 👋 

**Discord Username** : Okinawa Ore Cream Milk Tea#9978

**Twitter Username** : @GiaTien33811247

**EVM Wallet Address** : 0xcf22Efde07e9365D5Ebe7f2854b683428f96e25e

![image](https://user-images.githubusercontent.com/110958388/183811856-c0332c88-b8a5-4179-ac01-8fc7b90d39e4.png)

**1 Community Management** 
- Manage and support Vietnamese community, support English community chat since 10th June

I have 438 discord messages from 21th May to 31th July :

![image](https://user-images.githubusercontent.com/110958388/183818296-d99f3ced-9dd3-44c3-8802-89e0100c2dab.png)

![image](https://user-images.githubusercontent.com/110958388/183815449-cc695caa-7ab7-4639-b87b-9b4a9c41c8e8.png)

- Send SBY testnet token to many Algem members during testnet period :

![image](https://user-images.githubusercontent.com/110958388/183815060-68422465-bfc1-43a4-a375-24ad0198ee96.png)

**2 VSM** 
- Translated and pinned 35 announcements in Discord to Vietnamese language from 10th June to 31th July

![image](https://user-images.githubusercontent.com/110958388/183818812-07346ca3-b58b-4ef6-b6c3-d43ae950aeff.png)

10th June : 
https://discord.com/channels/949531419619766332/981177140680753182/984830263831965706

31th July :
https://discord.com/channels/949531419619766332/981177140680753182/1003210559157698571

**Comment by Gunit2481** [comment]
Hi Okinawa.

Thank you for submitting your work, points were added to the spreadsheet!
