### ISSUE TITLE
August 2022 contribution (Mutant)

### ISSUE THREAD

**Issue by MMUTANTT** [AlgemDeFi/Algyors-Program#12]
Twitter: main https://twitter.com/artifckd
Russian twitter algem: https://twitter.com/AlgemRussia
Discord: MUTANT#7180
EVM Wallet Address: 0xf1A340456992e665a433CF63f787Bfac1dA45750
Medium: 1) https://bit.ly/3q2iUJa
2) https://bit.ly/3cEMO31
3)https://bit.ly/3RoPyQB
4)https://bit.ly/3QbdpSN
Notion: Added full RU FAQ https://creative-cotija-c41.notion.site/9cfddfa8ea104491a1b7b3a8feeb25e2
Kagla finance page https://creative-cotija-c41.notion.site/Kagla-Finance-57d3c515d7d246aaa74cf70068aa72a5
2 meme: 
![meme alg](https://user-images.githubusercontent.com/110470191/187884435-669147fd-1b7e-4f6a-98cd-f4d2115e7ac5.JPG)
![alg me](https://user-images.githubusercontent.com/110470191/187884439-decea6e6-c56a-4678-afad-70292eaa0035.JPG)
discord active:
![active](https://user-images.githubusercontent.com/110470191/187884684-b13e2862-a5de-4586-a34b-a7a334ab5d46.JPG)
twitter main active: more than 10 publications

**Comment by Gunit2481** [comment]
Hi Mutant,

Thank you for your contributions. Points were added to the spreadsheet.

Please, for the next month, try to follow the guidelines and keep everything to one issue.

E.g.:

Community Management
Algem's envoy
The Professor
It's much easier for us to evaluate correctly your work. 💪

Thank you!
