### ISSUE TITLE
August 2022 contribution (GuiGou)

### ISSUE THREAD

**Issue by GuiGou12358** [AlgemDeFi/Algyors-Program#13]
Hello Algem Team

Discord Username : GuiGou#1021
Twitter Username : @GuiGou12358
EVM Wallet Address : 0x873De45Cb8453144a8BC76c2916DD9c52a9Bdb34

1) Community Management

 - Active in discord

![image](https://user-images.githubusercontent.com/92046056/188082098-6fff5603-1739-440d-9f70-310c2d178881.png)

 - Manage the space Algem in subsocial
       https://app.subsocial.network/7221

 - Active in Astar Forum
      https://forum.astar.network/t/nastr-unbonding-issue-clarity-of-algem-sirius-finance-nastr-use/3880

2) Algem's envoy

- Translate articles in subsocial

https://app.subsocial.network/7241/algem-construit-le-hub-de-liquidite-pour-polkadot-et-astar-35411
https://app.subsocial.network/7241/tout-ce-que-vous-devez-savoir-sur-le-staking-liquide-sur-le-35412

3) Extra task (Content Creator or The Professor?)

https://twitter.com/GuiGou12358/status/1555240083200040961?s=20&t=nZL1vaNXbIVEW4Bu1H45OQ

**Comment by Gunit2481** [comment]
Hi GuiGou,

Thank you for submitting your contributions. Points were added to the spreadsheet!
