### ISSUE TITLE
August 2022 Contribution ( ChikaIzumi )

### ISSUE THREAD

**Issue by ChikaIzumi** [AlgemDeFi/Algyors-Program#14]
Discord username : ChikaIzumi#0784
Twitter username : @Algem_Thai /@NyiNyiW18365837
EVM wallet address : 0x795712AeD2fe361b3623861903c916c8596E2733

**Contribution** :

1. **Community management**

- Help and active in the Discord community!

#general/main chat
![IMG_20220906_145725](https://user-images.githubusercontent.com/110775141/188587806-e8dd861e-1500-4ba3-b1a8-0d6030e0cfc5.jpg)
![IMG_20220906_145340](https://user-images.githubusercontent.com/110775141/188587856-e7b6622c-cbdd-4c90-b5cc-a5388110a85c.jpg)

#Thai channel
![IMG_20220906_145400](https://user-images.githubusercontent.com/110775141/188588057-cc64cf4c-82b0-4151-88ae-f71bdae380c8.jpg)

- Manage the Thai represented local communities!
Twitter - https://twitter.com/Algem_Thai?s=09
Medium - https://medium.com/@Algem_Thai

2. **VSM**

- https://bit.ly/3RlOzkM
- https://bit.ly/3RHDJ8C
- https://bit.ly/3cSz7O3
- https://bit.ly/3ARwcgD
- https://bit.ly/3APJEkT
- https://bit.ly/3wUCx9D
- https://bit.ly/3Q67w9s
- And translate  All major Discord announcements to Local language 🇹🇭 (#Thai channel)

3. **The Professor** (Twitter thread)

-https://twitter.com/NyiNyiW18365837/status/1555138932458696704?s=20&t=kANrl8sY0OOEzxnspYexmw

- ( And Engage all twitter tweets of Algem) also👇🏻
- https://twitter.com/NyiNyiW18365837/status/1555598660288663552?s=20&t=kANrl8sY0OOEzxnspYexmw
- https://twitter.com/NyiNyiW18365837/status/1559085589919453185?s=20&t=kANrl8sY0OOEzxnspYexmw
- https://twitter.com/NyiNyiW18365837/status/1559857509472432128?s=20&t=kANrl8sY0OOEzxnspYexmw 

4. **Artistic Contents** ( meme )

- https://discord.com/channels/949531419619766332/949539197323194478/1004453893608046693
![IMG_20220804_004352-1](https://user-images.githubusercontent.com/110775141/188596363-3754c8ef-1fdd-4556-9c88-e860cf0ca490.png)

- https://discord.com/channels/949531419619766332/949539197323194478/1013141471743987812
![algem_meme](https://user-images.githubusercontent.com/110775141/188596537-6a1f86c3-f866-4d4f-8df2-cb8f0bebbce1.png)

**Comment by Gunit2481** [comment]
Hi Chikalzumi,

Thank you for your contributions, points were added to the spreadsheet.

Keep up the hard work. 💪
