### ISSUE TITLE
August 2022 Contribution ( Robin58 )

### ISSUE THREAD

**Issue by AlgemIndonesia** [AlgemDeFi/Algyors-Program#15]
Discord username : Robin58#0059
Twitter username : @Algem_Indonesia
EVM wallet address : 0xE97B47D88d7071Ddc107EA7039Ae388698Da504D

**Contribution :** 

**1. Community Management**
- Help and answer the community on server Discord #ID-Indonesia
![Screenshot 2022-09-06 093058](https://user-images.githubusercontent.com/107385646/188698120-3df45de2-f6b6-4b27-b1ef-a37a5327a3b7.png)

- Update on Twitter https://twitter.com/Algem_Indonesia
![Screenshot 2022-09-06 094313](https://user-images.githubusercontent.com/107385646/188698316-05393df3-d58c-4b5f-8ac0-646b6cf78b57.png)
![Screenshot 2022-09-06 093608](https://user-images.githubusercontent.com/107385646/188698349-c7c9a246-2e3c-4016-89b5-1bd878e5f30f.png)
_`(Twitter Analytics Date : 1 - 30 August)`_

- Update on Telegram https://t.me/Algem_Indonesia
![Screenshot 2022-09-06 095841](https://user-images.githubusercontent.com/107385646/188698608-3964efa8-2ad6-43cb-bfb0-c52412261879.png)

**2. Algem's Envoy** 
https://twitter.com/Algem_Indonesia/status/1555248410902810624
https://twitter.com/Algem_Indonesia/status/1555248794811629568
https://twitter.com/Algem_Indonesia/status/1555250959290609664
https://twitter.com/Algem_Indonesia/status/1556997044166094849
https://twitter.com/Algem_Indonesia/status/15573349848467660
https://twitter.com/Algem_Indonesia/status/156354725006365901081
https://twitter.com/Algem_Indonesia/status/1558411037212573696
https://twitter.com/Algem_Indonesia/status/1558411494706278402
https://twitter.com/Algem_Indonesia/status/1559457792682995713
_(Discord and Telegram upload at the same with twitter)_

**3. VSM** 
https://medium.com/@Algem_Indonesia/algem-ama-dengan-jaringan-astar-d372be61956b
https://medium.com/@Algem_Indonesia/analgemaugust-sudah-siaran-langsung-84d5ecba1c03

**4. The Professor** ( Tutorial/Thread )
https://twitter.com/Algem_Indonesia/status/1555248794811629568
https://twitter.com/Algem_Indonesia/status/1557334243872714752
https://twitter.com/Algem_Indonesia/status/1563551011209244675

**Comment by Gunit2481** [comment]
Hi Robin,

Thank you for your contribution, points were added to the spreadsheet.

FYI, the VSM and the Algem Envoy are the same thing, so for the next month, you can just write everything down under "Algem Envoy".
