### ISSUE TITLE
August 2022 Contribution ( IeyasuTokugawa) 

### ISSUE THREAD

**Issue by IeyasuTokugawa** [AlgemDeFi/Algyors-Program#16]
Discord username : IeyasuTokugawa#0815
Twitter username : @Algem_io_jp /@ma_crypt
EVM wallet address : 0x71a8e3474EFf7302D67B4c474540D2124586B4f9

1 Contribution :

Community management
Help and active in the Discord community!
main/Japanese channel
<img width="497" alt="スクリーンショット 2022-09-07 19 45 59" src="https://user-images.githubusercontent.com/104721247/188859908-154d1533-94d7-4964-bec9-a91952383e85.png">
<img width="449" alt="スクリーンショット 2022-09-07 19 46 37" src="https://user-images.githubusercontent.com/104721247/188860027-4a7717b2-a882-491f-9162-b8d6834aad3d.png">
<img width="438" alt="スクリーンショット 2022-09-07 19 46 45" src="https://user-images.githubusercontent.com/104721247/188860038-401b6789-ec4d-41ca-bf6e-aa759d689e03.png">

Manage the Japan represented local communities
Twitter - https://twitter.com/Algem_io_jp
Medium - https://medium.com/@algem.jp

2 VSM
・https://medium.com/@algem.jp/%E6%8F%90%E6%90%BA%E7%99%BA%E8%A1%A8-algem%E3%81%AFkagla%E3%81%A8%E6%8F%90%E6%90%BA%E3%81%97astar-network%E3%81%AEdefi%E3%82%A8%E3%82%B3%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0%E3%81%A7-nastr%E3%83%9B%E3%83%AB%E3%83%80%E3%83%BC%E3%81%AB%E8%BF%BD%E5%8A%A0%E3%81%AE%E5%8F%8E%E7%9B%8A%E6%BA%90%E3%82%92%E6%8F%90%E4%BE%9B%E3%81%97%E3%81%BE%E3%81%99-a2daa486dde1
・https://medium.com/@algem.jp/algem%E3%81%AF-polkadot%E3%81%A8astar-network%E3%81%AE%E3%81%9F%E3%82%81%E3%81%AE%E6%B5%81%E5%8B%95%E6%80%A7hub%E3%82%92%E6%A7%8B%E7%AF%89%E3%81%97%E3%81%A6%E3%81%84%E3%81%BE%E3%81%99-%E6%88%91%E3%80%85%E3%81%AE%E9%95%B7%E6%9C%9F%E7%9A%84%E3%81%AA%E3%83%93%E3%82%B8%E3%83%A7%E3%83%B3-6d4e6864cc0a
・https://medium.com/@algem.jp/%E7%99%BA%E8%A1%A8-an-algem8%E6%9C%88-%E3%81%93%E3%82%8C%E3%81%AF%E3%81%82%E3%81%AA%E3%81%9F%E3%81%8C%E5%AE%9F%E9%9A%9B%E3%81%AB%E6%AC%B2%E3%81%97%E3%81%84%E5%B7%A8%E5%A4%A7%E3%81%AA%E3%82%A4%E3%83%B3%E3%82%BB%E3%83%B3%E3%83%86%E3%82%A3%E3%83%96%E3%82%AD%E3%83%A3%E3%83%B3%E3%83%9A%E3%83%BC%E3%83%B3%E3%81%A7%E3%81%99-fe56cc3b8872
・https://medium.com/@algem.jp/algem-ama-with-astar-network-1f04b416fbed
・And translate All major Discord announcements to Local language  (#Japan channel)

・The Professor (Twitter thread)
https://twitter.com/Algem_io_jp/status/1558097489127174144?s=20&t=eu8lw2Z2HYNXk32BcUJ-0w

・Translation and maintenance of the Algem FAQ
https://discord.com/channels/949531419619766332/981176955741294602/997179975675424889

**Comment by Gunit2481** [comment]
Hello Shogun,

Thank you for submitting your work.

Great work!
