### ISSUE TITLE
August 2022 Contribution (Okinawa Oreo Cream Milk Tea)

### ISSUE THREAD

**Issue by OkinawaOreoCreamMilkTea** [AlgemDeFi/Algyors-Program#17]
Hello Algem admins 👋

**Discord Username :** Okinawa Ore Cream Milk Tea#9978

**Twitter Username :** @GiaTien33811247

**EVM Wallet Address :** 0xcf22Efde07e9365D5Ebe7f2854b683428f96e25e

![image](https://user-images.githubusercontent.com/110958388/188851781-7fec3d1a-4306-4395-aaeb-adc4c78a964f.png)

**1 Community Management**

* Manage Vietnamese channel , help and active both Vietnamese and General channel

I have 160 discord messages on August :

![image](https://user-images.githubusercontent.com/110958388/188852085-385aa1ec-5e52-401c-aa85-6bd0df556b40.png)

* Twitter ( but this account is temporarily restricted )
[https://twitter.com/Algem_Vietnam](url)

![image](https://user-images.githubusercontent.com/110958388/188852823-64fd6467-4ee3-4a4b-a76f-8531ff456af5.png)

* Medium :
[https://medium.com/@Algem_Vietnam](url)

**2 VSM**

* Translated 34 announcements in Discord to Vietnamese

![image](https://user-images.githubusercontent.com/110958388/188861511-f2eaca10-b5d9-406f-9aa7-4f0cd2323ee8.png)

* Translated 7 Algem Blogs to Vietnamese Medium : 
[https://medium.com/@Algem_Vietnam](url)

* **BONUS :**
Translated the whole Algem docs to Vietnamese with the ratio 1:1 :
[https://okinawa-oreo-cream-milk-tea.gitbook.io/tai-lieu-algem-viet-nam/](url)

**3 Content Creator**

* Wrote a Twitter thread about Algem in Vietnamese :
[https://twitter.com/GiaTien33811247/status/1564964982865162240](url)

**4 The Professor**

Vietnamese turtorial how to use Algem, stake nASTR , Metamask , Polkadot wallet , transfer ASTR to Astar Network
[https://okinawa-oreo-cream-milk-tea.gitbook.io/tai-lieu-algem-viet-nam/nguoi-moi-bat-dau/mang-va-vi](url)
[https://okinawa-oreo-cream-milk-tea.gitbook.io/tai-lieu-algem-viet-nam/nguoi-moi-bat-dau/chuyen-tai-san-sang-mang-astar](url)
[https://okinawa-oreo-cream-milk-tea.gitbook.io/tai-lieu-algem-viet-nam/nguoi-moi-bat-dau/cach-su-dung-algems-de-dat-coc-liquid](url)

**5 The Artist**

* 8 Memes :
1 : [https://discord.com/channels/949531419619766332/949539197323194478/1013091146592948235](url)
2 to 8 : 
[https://discord.com/channels/949531419619766332/949539197323194478/1013720484933804074](url)
[https://discord.com/channels/949531419619766332/949539197323194478/1014382417819209728](url)

* Won the second place ART competition on Discord with this :

![image](https://user-images.githubusercontent.com/110958388/188867238-289c5488-e0ee-45a1-8480-569386bded94.png)

**Comment by Gunit2481** [comment]
Hi Okinawa,

Thank you for your contributions, it's a really good job for August!
Points were added to the spreadsheet.

Keep up the hard work. 💪
