### ISSUE TITLE
September 2022 Contribution ( ChikaIzumi )

### ISSUE THREAD

**Issue by ChikaIzumi** [AlgemDeFi/Algyors-Program#18]
Discord Username : ChikaIzumi#0784
Twitter Username : @Algem_Thai @Nyibo_Og
Evm Wallet Address : 0x795712AeD2fe361b3623861903c916c8596E2733

**Contribution** : 

1. **Community Management**

- Help and Active in discord channels.

- 
![IMG_20221003_213440](https://user-images.githubusercontent.com/110775141/193612642-dafc1aee-e74c-49a8-9fed-e465f9241e10.jpg)
![IMG_20221003_213420](https://user-images.githubusercontent.com/110775141/193612659-08fbe3e5-0553-4a1a-9a1d-ba3193a7f1e0.jpg)

- Here 😄
![IMG_20221003_214111](https://user-images.githubusercontent.com/110775141/193612922-50117a13-401e-49af-903f-b7e474cfc59b.jpg)

-  Manage local communities:
Twitter - https://twitter.com/Algem_Thai?s=09
Medium - https://medium.com/@Algem_Thai

2. **VSM**

- https://bit.ly/3QmZkSI
- https://bit.ly/3TQE0rD
- https://bit.ly/3QwAqQB
- https://bit.ly/3Drs0a4
- https://bit.ly/3rh5DNb
- And translate All major Discord announcements to local language 🇹🇭

3. **Content Creator**

- https://twitter.com/Nyibo_Og/status/1575811254827950080?s=20&t=UhTWaxe7y1QsvljDnaAhpA
- https://twitter.com/Nyibo_Og/status/1568221522426302465?t=2VSvIHnUp84CUqW7VhQ0lA&s=19

4. **Artistic Content** - 5 memes

- https://discord.com/channels/949531419619766332/949539197323194478/1015872133643108412
- https://discord.com/channels/949531419619766332/949539197323194478/1024253393205739601
- https://discord.com/channels/949531419619766332/949539197323194478/1025289068256440371
- https://discord.com/channels/949531419619766332/949539197323194478/1025460143737012325

**Comment by Gunit2481** [comment]
Hi Chikalzumi,

Points were added to the spreadsheet, thank you for being really present and helping on Discord.

Good job!
