### ISSUE TITLE
September 2022 contribution (GuiGou) 

### ISSUE THREAD

**Issue by GuiGou12358** [AlgemDeFi/Algyors-Program#19]
Hello Algem Team

Discord Username : GuiGou#1021
Twitter Username : @GuiGou12358
EVM Wallet Address : 0x873De45Cb8453144a8BC76c2916DD9c52a9Bdb34

Community Management
Active in discord
![image](https://user-images.githubusercontent.com/92046056/194019731-fee44712-2798-4775-bb4a-338aa1e8c888.png)

Hoping to understand well and share the vision and goal of Algem
![image](https://user-images.githubusercontent.com/92046056/194021867-fc8b6b09-a67a-412b-b811-c6d07d3c8bd5.png)

Manage the space Algem in subsocial
https://app.subsocial.network/7221

Algem's envoy
Translate articles in subsocial
https://app.subsocial.network/7241/les-contrats-adapter-sont-lances-sur-algem-35703
https://app.subsocial.network/7241/le-guide-ultime-de-l-ecosysteme-de-fi-du-reseau-astar-7-35704

Translate the scripts for the video

**Comment by Gunit2481** [comment]
Hi Guigou!

Thank you for your work and also for representing Algem on Subsocial!

Well done.
