### ISSUE TITLE
September 2022 contribution (Robin58)

### ISSUE THREAD

**Issue by AlgemIndonesia** [AlgemDeFi/Algyors-Program#20]
Discord Username : Robin58#0059
Twitter Username : @Algem_Indonesia
EVM Wallet Address : 0xE97B47D88d7071Ddc107EA7039Ae388698Da504D

**1. Community Management**

- Discord 

Community on server #ID-Indonesia
![Screenshot 2022-10-05 215221](https://user-images.githubusercontent.com/107385646/194217130-3b14277c-5fc1-4e2a-ada3-ea2d362b5d5d.png)

Rank on discord
![Screenshot 2022-10-05 215354](https://user-images.githubusercontent.com/107385646/194217392-c5c7deea-5227-4757-bed1-9169512c5a7b.png)

- Twitter

https://twitter.com/Algem_Indonesia
![Screenshot 2022-10-05 215735](https://user-images.githubusercontent.com/107385646/194217897-0849ba85-72dd-4e86-a251-79a70d1045e8.png)

- Medium https://medium.com/@Algem_Indonesia
-  Telegram https://t.me/Algem_Indonesia

**2. VSM**

- https://medium.com/@Algem_Indonesia/di-sini-kontrak-adaptor-diluncurkan-di-algem-1c04aaddbfa
- https://medium.com/@Algem_Indonesia/peluncuran-kemitraan-algem-bekerja-sama-dengan-kagla-untuk-memberikan-aliran-pendapatan-tambahan-2ad9a3d9e4be
- https://medium.com/@Algem_Indonesia/panduan-utama-untuk-ekosistem-defi-jaringan-astar-7-proyek-yang-perlu-anda-ketahui-a664fdcf3049

**3. Content Creator**
- https://docs.google.com/spreadsheets/d/1zxvI-Wu2mn-1w93o_04I7Il2jWCVK8BthyoWXskHUyM/edit#gid=1907506039
(Translate language to indonesia)

**Comment by Gunit2481** [comment]
Hi Robin,

Thank you for your contributions, points were added to the spreadsheet.

Well done!
