### ISSUE TITLE
September 2022 contribution (MUTANT)

### ISSUE THREAD

**Issue by MMUTANTT** [AlgemDeFi/Algyors-Program#21]
Discord Username : MUTANT#7180
Twitter Username : https://twitter.com/AlgemRussia , https://twitter.com/artifckd
Evm Wallet Address : 0xf1A340456992e665a433CF63f787Bfac1dA45750

Contribution :

1. Community Management
Help and Active in discord channels.
![ghju](https://user-images.githubusercontent.com/110470191/194249962-c9f3d19e-af60-4e16-8e01-b1dce80c30e5.JPG)

Manage local communities:
Medium: https://medium.com/@peacedukeprodaction
Twitter: https://twitter.com/AlgemRussia

2. VSM
https://bit.ly/3SIqF3t
https://bit.ly/3SHVOE6
https://bit.ly/3CCPLvd
https://bit.ly/3CD33Yu
https://bit.ly/3REdkrO
https://bit.ly/3RFjS9x
And also a full translation of all news in my language (Russian)

3. Content Creator
https://twitter.com/artifckd/status/1568898735752597505

4. Artistic content 3 memes
https://discord.com/channels/949531419619766332/949539197323194478/1022851241715445770
https://discord.com/channels/949531419619766332/949539197323194478/1021373255526920203
https://discord.com/channels/949531419619766332/949539197323194478/1018454436563128350

**Comment by Gunit2481** [comment]
Hi Mutant,

Thank you for being really active on Discord and helping the community. Points were added to the spreadsheet.

Really good job!
