### ISSUE TITLE
September 2022 contribution (Okinawa Oreo Cream Milk Tea)

### ISSUE THREAD

**Issue by OkinawaOreoCreamMilkTea** [AlgemDeFi/Algyors-Program#22]
Hello Algem admins 👋

**Discord Username** : Okinawa Ore Cream Milk Tea#9978

**Twitter Username** : @GiaTien33811247

**EVM Wallet Address** : 0xcf22Efde07e9365D5Ebe7f2854b683428f96e25e

![image](https://user-images.githubusercontent.com/110958388/194476861-e37f014f-68da-4407-a7f2-210296d069a8.png)

**1 Community Management**

* Manage Vietnamese channel , help and active both Vietnamese and General channel

I have **239 discord messages** on September (more than August , rank 1) :

![image](https://user-images.githubusercontent.com/110958388/194479399-890ffd05-c398-4f72-80f4-90e0191ae730.png)

* Twitter ( this account is temporarily restricted )

* Update on Medium :
https://medium.com/@Algem_Vietnam

**2 VSM**

* Translated **37 announcements** in Discord to Vietnamese

![image](https://user-images.githubusercontent.com/110958388/194480321-0eb51650-1440-42d2-af6a-c775a1710a25.png)

* Translated Algem Blogs to Vietnamese Medium

**3 The Artist**

* I have created and posted **10 Memes** during September :
1 https://discord.com/channels/949531419619766332/949539197323194478/1021381382641029220
2 https://discord.com/channels/949531419619766332/949539197323194478/1022511715939782696
3 https://discord.com/channels/949531419619766332/949539197323194478/1022511813591580732
4 https://discord.com/channels/949531419619766332/949539197323194478/1023254490155065374
5 https://discord.com/channels/949531419619766332/949539197323194478/1023615253927428218
6 https://discord.com/channels/949531419619766332/949539197323194478/1024297567674183730
7 https://discord.com/channels/949531419619766332/949539197323194478/1024354280934748311
8 https://discord.com/channels/949531419619766332/949539197323194478/1025006908228247552
9 https://discord.com/channels/949531419619766332/949539197323194478/1025370774934138980
10 https://discord.com/channels/949531419619766332/949539197323194478/1025445384908189808

**Comment by Gunit2481** [comment]
Hi Okinawa,

Well done on all these memes, I love them! Points were added to the spreadsheet.

Great job
