### ISSUE TITLE
September 2022 contribution (Ieyasu Tokugawa)

### ISSUE THREAD

**Issue by IeyasuTokugawa** [AlgemDeFi/Algyors-Program#23]
Discord Username : IeyasuTokugawa#0815
Twitter Username : @Algem_io_jp @ma_crypt
Evm Wallet Address : 0x71a8e3474EFf7302D67B4c474540D2124586B4f9

**Contribution :**

Community Management
Help and Active in discord channels.
<img width="438" alt="スクリーンショット 2022-10-08 0 58 13" src="https://user-images.githubusercontent.com/104721247/194597094-d1b0a02e-e348-4a5d-85d5-1df048fa142c.png">

<img width="635" alt="スクリーンショット 2022-10-08 0 59 05" src="https://user-images.githubusercontent.com/104721247/194597240-33b12ddf-6e99-4946-ac41-cc3c34b27f81.png">

<img width="629" alt="スクリーンショット 2022-10-08 0 59 40" src="https://user-images.githubusercontent.com/104721247/194597343-02b6f152-23f7-4318-b6ec-d56cac3efa66.png">

Manage local communities:
Twitter - https://twitter.com/Algem_io_jp
Medium - https://medium.com/@algem.jp

**VSM**
・https://medium.com/@algem.jp/astar-network-defi%E3%82%A8%E3%82%B3%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0%E3%81%AE%E7%A9%B6%E6%A5%B5%E3%81%AE%E3%82%AC%E3%82%A4%E3%83%89-%E7%9F%A5%E3%81%A3%E3%81%A6%E3%81%8A%E3%81%8F%E3%81%B9%E3%81%8D7%E3%81%A4%E3%81%AE%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88-b405f9a4c4be
・https://medium.com/@algem.jp/algem%E3%81%8Cequilibriums-beta%E3%81%AB%E5%8F%82%E5%8A%A0-%E8%B1%AA%E8%8F%AF%E8%B3%9E%E5%93%81%E3%81%8C%E5%BD%93%E3%81%9F%E3%82%8B%E3%82%AD%E3%83%A3%E3%83%B3%E3%83%9A%E3%83%BC%E3%83%B3%E5%AE%9F%E6%96%BD%E4%B8%AD-f569f8ace1c

<img width="1317" alt="スクリーンショット 2022-10-08 1 05 09" src="https://user-images.githubusercontent.com/104721247/194598332-e83dbc1b-1542-4e2c-9677-7c7f6a2b5252.png">

And translate All major Discord announcements to local language Japanese channel

And AMA meeting with Shunp and You, preparation, inviting AMA participants
https://twitter.com/Algem_io/status/1575817767852253184?s=20&t=-sqs4kMm87FRfRZcGHFjtQ

**Content Creator**
<img width="629" alt="スクリーンショット 2022-10-08 0 59 40" src="https://user-images.githubusercontent.com/104721247/194597958-717bdec2-ff98-446d-a7b1-b39d036543b3.png">
[
](https://discord.com/channels/949531419619766332/949539197323194478/1018515751402999858)

**Comment by Gunit2481** [comment]
Hi Shogun,

Thank you for doing this AMA with You and Shun. Points were added to the spreadsheet.

Good job!
