### ISSUE TITLE
October 2022 contribution (GuiGou)

### ISSUE THREAD

**Issue by GuiGou12358** [AlgemDeFi/Algyors-Program#24]
Hello Algem Team

Discord Username : GuiGou#1021
Twitter Username : @GuiGou12358
EVM Wallet Address : 0x873De45Cb8453144a8BC76c2916DD9c52a9Bdb34

Community Management
Active in discord
![image](https://user-images.githubusercontent.com/92046056/199452608-463d665a-6494-47f0-ac71-4e002141ae10.png)

Active in other channel
![image](https://user-images.githubusercontent.com/92046056/199453698-99a25dd3-62c6-4d71-9c5e-ef1a6913ba1d.png)

Manage the space Algem in subsocial
https://app.subsocial.network/7221

Algem's envoy
Translate articles in subsocial
https://app.subsocial.network/7241/comment-utiliser-le-n-astr-liquidity-hub-d-algem-35922

**Comment by Gunit2481** [comment]
Hi Guigou,

Thank you for your contribution and for managing Algem's subsocial.

Points were added to the spreadsheet.
