### ISSUE TITLE
October 2022 contribution (MUTANT) 

### ISSUE THREAD

**Issue by MMUTANTT** [AlgemDeFi/Algyors-Program#25]
Discord Username : MUTANT#7180
Twitter Username : https://twitter.com/AlgemRussia , https://twitter.com/artifckd
Evm Wallet Address : 0xf1A340456992e665a433CF63f787Bfac1dA45750

Contribution :

1. Community Management
Help and Active in discord channels.
![profalg](https://user-images.githubusercontent.com/110470191/199702694-29b0cb82-1469-49f1-920f-67a4726aebd3.JPG)
Manage local communities:
Medium: https://medium.com/@peacedukeprodaction
Twitter: https://twitter.com/AlgemRussia

2. VSM
https://bit.ly/3NLgI3T
https://bit.ly/3hbYYm0
https://bit.ly/3U3IxX9
And also a full translation of all news in my language (Russian)

3. Artistic content 4 memes
https://discord.com/channels/949531419619766332/949539197323194478/1035514743965876354
https://discord.com/channels/949531419619766332/949539197323194478/1034405339619139625
https://discord.com/channels/949531419619766332/949539197323194478/1032008849298817064
https://discord.com/channels/949531419619766332/949539197323194478/1028667134097756210

**Comment by Gunit2481** [comment]
Hi Mutant,

Thank you for your work, points were added to the spreadsheet.
