### ISSUE TITLE
October 2022 Contribution (Robin58)

### ISSUE THREAD

**Issue by AlgemIndonesia** [AlgemDeFi/Algyors-Program#26]
Discord Username: Robin58#0059
Twitter Username: @Algem_Indonesia
EVM Wallet Address: 0xE97B47D88d7071Ddc107EA7039Ae388698Da504D

**1. Community Management**
- Active on Discord
![Screenshot 2022-11-03 205153](https://user-images.githubusercontent.com/107385646/199881810-630d84cf-8375-4784-98ce-351feec84454.png)

- Twitter
![Screenshot 2022-11-03 205352](https://user-images.githubusercontent.com/107385646/199881938-307a5c73-1cb1-45ce-a64e-34cd69e69cd9.png)

-Telegram 
![Screenshot 2022-11-03 205453](https://user-images.githubusercontent.com/107385646/199882044-aefcc58c-83f1-4f80-a779-d360ec5e6976.png)

**2. VSM**
-https://medium.com/@Algem_Indonesia/cara-menggunakan-pusat-likuiditas-nastr-algem-3da5ad3b6962

-https://medium.com/@Algem_Indonesia/penting-investasi-anda-di-algem-semakin-aman-b7acc243d266

-https://medium.com/@Algem_Indonesia/menangkan-hadiah-luar-biasa-dengan-kontes-kemitraan-algem-dan-archiverse-sekarang-c197746c7cf3

**3. The Artist**
https://twitter.com/Algem_Indonesia/status/1584193270657130496?t=ex5ytdvvC-CeTJUFpA94Bg&s=19
![image](https://user-images.githubusercontent.com/107385646/199882805-3c390d3d-139b-4ee6-bb3f-b6ec04b90c2f.png)

**Comment by Gunit2481** [comment]
Hi Robin.

Great job! Points were added to the spread sheet.
