### ISSUE TITLE
October 2022 Contribution (IeyasuTokugawa#0815)

### ISSUE THREAD

**Issue by IeyasuTokugawa** [AlgemDeFi/Algyors-Program#27]
Discord Username: IeyasuTokugawa#0815
Twitter Username: @Algem_io_jp
EVM Wallet Address: 0x71a8e3474EFf7302D67B4c474540D2124586B4f9

1. Community Management
Active on Discord
<img width="1660" alt="スクリーンショット 2022-11-04 14 25 50" src="https://user-images.githubusercontent.com/104721247/199896705-1b7d0b1a-7e7a-48a3-b783-45238feaa35d.png">

Twitter
<img width="1503" alt="スクリーンショット 2022-11-04 14 26 21" src="https://user-images.githubusercontent.com/104721247/199896795-acde3216-1db3-4ca1-a790-811d9c1c09b8.png">

2. VSM
https://medium.com/@algem.jp/%E9%87%8D%E8%A6%81-algem%E3%81%B8%E3%81%AE%E6%8A%95%E8%B3%87%E3%81%AF%E3%82%88%E3%82%8A%E5%AE%89%E5%85%A8%E3%81%AB%E3%81%AA%E3%82%8A%E3%81%BE%E3%81%97%E3%81%9F-4b38074f9e56

https://medium.com/@algem.jp/algem%E3%81%A8archiverse%E3%81%AE%E3%83%91%E3%83%BC%E3%83%88%E3%83%8A%E3%83%BC%E3%82%B7%E3%83%83%E3%83%97%E3%81%A7%E8%B1%AA%E8%8F%AF%E8%B3%9E%E5%93%81%E3%81%8C%E5%BD%93%E3%81%9F%E3%82%8B%E3%82%B3%E3%83%B3%E3%83%86%E3%82%B9%E3%83%88%E9%96%8B%E5%82%AC%E4%B8%AD-7aa69a506c86

3.AMA
<img width="1330" alt="スクリーンショット 2022-11-04 14 29 01" src="https://user-images.githubusercontent.com/104721247/199897130-b80ff502-e101-42b3-8b2d-a01fd08025f5.png">

**Comment by Gunit2481** [comment]
Hi Shogun,

Thanks for your contribution and a great job doing this AMA with Shun and the Japanese community!

Points were added to the spreadsheet.
