### ISSUE TITLE
October 2022 Contribution (Okinawa Oreo Cream Milk Tea)

### ISSUE THREAD

**Issue by OkinawaOreoCreamMilkTea** [AlgemDeFi/Algyors-Program#28]
Hello Algem admins 👋

**Discord Username** : Okinawa Ore Cream Milk Tea#9978

**Twitter Username** : @GiaTien33811247

**EVM Wallet Address** : 0xcf22Efde07e9365D5Ebe7f2854b683428f96e25e

![image](https://user-images.githubusercontent.com/110958388/194476861-e37f014f-68da-4407-a7f2-210296d069a8.png)

**1 Community Management**

* Manage Vietnamese channel , help and active both Vietnamese and General channel

I have **319 discord messages** on October (more than September) :

![image](https://user-images.githubusercontent.com/110958388/200242872-cf28324f-87b0-45c7-b936-3f88018d9add.png)

* Update on Medium :
https://medium.com/@Algem_Vietnam

**2 VSM**

* Translated **33 announcements** in Discord to Vietnamese

![image](https://user-images.githubusercontent.com/110958388/200243425-ab1a244c-7404-4ece-95c1-6d678c1bafb5.png)

* Translated Algem Blogs to Vietnamese Medium

**3 The Artist**

* I have created and posted **3 Memes** during October :

1 https://discord.com/channels/949531419619766332/949539197323194478/1035508499922296865
2 https://discord.com/channels/949531419619766332/949539197323194478/1030085637459685446
3 https://discord.com/channels/949531419619766332/949539197323194478/1026853113207992350

**Comment by Gunit2481** [comment]
Hi Okinawa,

Thank you for your work and help on Algem's Discord. However, I didn't count your Memes in your contribution for this month because they were not about Algem. 

Points were added to the spreadsheet.
