### ISSUE TITLE
October 2022 Contribution ( ChikaIzumi )

### ISSUE THREAD

**Issue by ChikaIzumi** [AlgemDeFi/Algyors-Program#29]
**Discord Username** : ChikaIzumi#0784
**Twitter Username** : @Algem_Thai
**Evm Wallet Address** : 0x795712AeD2fe361b3623861903c916c8596E2733

**Contribution**

1. **Community Management**

- Help and Active in discord channels.
- 
![IMG_20221108_114216](https://user-images.githubusercontent.com/110775141/200480876-a0d54fc4-6f0c-4659-864d-6e67f20d0216.jpg)

- Manage local communities:
Twitter - https://twitter.com/Algem_Thai?s=09
Medium - https://medium.com/@Algem_Thai

2. **VSM**

- https://bit.ly/3Ctw33s
- https://bit.ly/3enKNsV
- https://bit.ly/3rLOFqL
- https://bit.ly/3SYaZsD
- And translate All major Discord announcements to Local language 🇹🇭 (#Thai channel)

3. **Artistic Content** - 3 memes

- https://discord.com/channels/949531419619766332/949539197323194478/1030770870219710494
- https://discord.com/channels/949531419619766332/949539197323194478/1030104696230268988
- https://discord.com/channels/949531419619766332/949539197323194478/1028622639029297182
- https://twitter.com/Nyibo_Og/status/1582446608192413696?t=xDlE7XbwVtdpkzqkEk8Y3w&s=19

**Comment by Gunit2481** [comment]
Hey Chikalzumi,

Thanks for your support on Discord and with our community.

Points were added to the spreadsheet.
