### ISSUE TITLE
June/July 2022 Contribution 

### ISSUE THREAD

**Issue by IeyasuTokugawa** [AlgemDeFi/Algyors-Program#6]
Discord Username: @IeyasuTokugawa#0815
Twitter Username: @ma_crypt/@Algem_io_jp                      
EVM Wallet Address: 0x71a8e3474EFf7302D67B4c474540D2124586B4f9

<img width="454" alt="スクリーンショット 2022-08-01 21 45 07" src="https://user-images.githubusercontent.com/104721247/182398570-a27898fe-351c-42b3-a562-767141829988.png">
DiscordMSG from June to July 31

<img width="1728" alt="スクリーンショット 2022-08-01 21 41 53" src="https://user-images.githubusercontent.com/104721247/182398769-6a6e8c5c-2796-47cd-b40c-2fc95e7d4487.png">
[Engagement with ]
[https://twitter.com/Algem_io_jp](url)

Engagement with Medium [https://medium.com/@algem.jp](url) (13 articles submitted）
<img width="1724" alt="スクリーンショット 2022-08-01 21 49 08" src="https://user-images.githubusercontent.com/104721247/182399633-e1e841a5-ac5e-4c3f-86b7-d1d507f78282.png">
<img width="1438" alt="スクリーンショット 2022-08-01 21 50 04" src="https://user-images.githubusercontent.com/104721247/182399641-6df87fbb-d70f-42f1-8a8b-21f336f614aa.png">
<img width="1301" alt="スクリーンショット 2022-08-01 21 50 17" src="https://user-images.githubusercontent.com/104721247/182399661-3549e06e-e45f-4a2c-9c61-8efd33627f32.png">

**Comment by Gunit2481** [comment]
Hello Shogun,

Thank you for submitting your work. 

Please, for the next month, try to follow the guidelines.

E.g.:

1. Community Management
2. Algem's envoy
3. The Professor

It's much easier for us to evaluate correctly your work. 💪

Thank you!
