### ISSUE TITLE
July 2022 contribution (Mutant) 

### ISSUE THREAD

**Issue by MMUTANTT** [AlgemDeFi/Algyors-Program#7]
Twitter: https://twitter.com/artifckd
Discord: MUTANT#7180
EVM Wallet Address: 0xf1A340456992e665a433CF63f787Bfac1dA45750
Medium: 1) https://medium.com/@peacedukeprodaction/algem-%D0%BE%D1%84%D0%B8%D1%86%D0%B8%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE-%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA%D0%B0%D0%B5%D1%82%D1%81%D1%8F-%D0%BD%D0%B0-soaring-polkadot-parachain-astar-network-9c3b13d8a7d5
2) https://medium.com/@peacedukeprodaction/algem-%D0%BF%D1%80%D0%BE%D1%88%D0%B5%D0%BB-%D0%BA%D1%80%D0%B8%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9-%D0%B0%D1%83%D0%B4%D0%B8%D1%82-%D1%81%D0%BC%D0%B0%D1%80%D1%82-%D0%BA%D0%BE%D0%BD%D1%82%D1%80%D0%B0%D0%BA%D1%82%D0%B0-%D0%B8-%D0%B1%D0%B5%D0%B7%D0%BE%D0%BF%D0%B0%D1%81%D0%BD%D0%BE%D1%81%D1%82%D0%B8-quantstamp-655cae98d428
Notion: Full translation Algem doc https://creative-cotija-c41.notion.site/Algem-8797ac9724d14aed8fc7900c999ccc4e
![tw1](https://user-images.githubusercontent.com/110470191/182425574-c4804cec-c51f-4ec8-9645-1b483d140940.JPG)
![tw2](https://user-images.githubusercontent.com/110470191/182425591-0f4b99ad-e4c0-42fb-8ad4-b4a6209ddfcb.JPG)
![tw3](https://user-images.githubusercontent.com/110470191/182425602-a30e448f-3398-45b6-b5cf-a82468e65678.JPG)
1 meme:
![algem](https://user-images.githubusercontent.com/110470191/182425692-a5d0a33f-434d-4b55-ab75-1a5e47f9614b.jpg)
discord activity:
![algemdis](https://user-images.githubusercontent.com/110470191/182425772-39f3a538-9e98-4059-ad73-f652cb18207a.JPG)

**Comment by Gunit2481** [comment]
Hi Mutant,

Thank you for your contributions. Points were added to the spreadsheet.

Great work with the documentation translation, I'll contact you later so we can add your work to the official documentation of Algem on Gitbook. 👏
