### ISSUE TITLE
July 2022 Contribution - Algem Indonesia (Robin)

### ISSUE THREAD

**Issue by AlgemIndonesia** [AlgemDeFi/Algyors-Program#9]
**Discord Username** : Robin58#0059
**Twitter Username** : @Algem_Indonesia
**EVM Wallet Addres** : 0xE97B47D88d7071Ddc107EA7039Ae388698Da504D

### **Contribution** :
1. Community Management 
- Active on discord server #ID-Indonesia
![516e4aaa-bc71-4b5b-a682-ad52de100a4c](https://user-images.githubusercontent.com/107385646/182679939-02837ff1-d335-43bf-be55-33bf1f81fed4.jpg)

- Update On Twitter https://twitter.com/Algem_Indonesia
![4e24b070-9f83-4e18-8baf-211a33f12107](https://user-images.githubusercontent.com/107385646/182680196-b830354d-6ff1-4f2b-88ab-225c7dbeb2f8.jpg)

- Update On Telegram Local https://t.me/Algem_Indonesia
![6bc81dd6-47d2-4df8-8b5e-39fcb8876e36](https://user-images.githubusercontent.com/107385646/182680994-a458e565-675b-46f3-b75b-3f9551f07a4f.jpg)

2. VSM 

- https://medium.com/@Algem_Indonesia/algem-dan-sirius-finance-bermitra-sebelum-peluncuran-3255545ccf8d
- https://medium.com/@Algem_Indonesia/algem-mengumumkan-kemitraan-dengan-sio2-finance-ec8cdf399427

3. Algem's Envoy
![b612d9b1-8be4-4c3f-a9e2-a6aedf937567](https://user-images.githubusercontent.com/107385646/182683828-8486cb54-d2a6-4271-8c8a-7294ba9b8f6c.jpg)

4. Professor
- https://medium.com/@Algem_Indonesia/algem-resmi-diluncurkan-di-soaring-polkadot-parachain-astar-network-5113467cf694
![1a841d5e-15f7-46cf-a215-d9b051bdbb5c](https://user-images.githubusercontent.com/107385646/182683175-350696dc-a5d2-4a22-aec7-43752db036da.jpg)

**Comment by Gunit2481** [comment]
Hi Robin,

Thank you for your contribution, points were added to the spreadsheet.

FYI, the VSM and the Algem Envoy are the same thing, so for the next month, you can just write everything down under "Algem Envoy".
